name: very_good_core
description: A Very Good App
version: 1.0.0+1
publish_to: none

environment: 
  sdk: ">=3.1.0 <4.0.0"
  flutter: ^3.13.9

dependencies:
  animations: ^2.0.8
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  chopper: ^7.0.8
  connectivity_plus: ^5.0.1
  crypto: ^3.0.3
  dartx: ^1.2.0
  email_validator: ^2.1.17
  faker: ^2.1.0
  flash: ^3.0.5+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_secure_storage: ^9.0.0
  flutter_web_plugins:
    sdk: flutter
  fpdart: ^1.1.0 
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4 
  go_router: ^12.0.0
  html_unescape: ^2.0.0
  http: ^1.1.0
  injectable: ^2.3.2
  intl: ^0.18.1
  intl_utils: ^2.8.5
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  pretty_chopper_logger: ^1.0.7
  responsive_framework: ^0.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  timeago: ^3.5.0
  url_launcher: ^6.2.1
  uuid: ^4.1.0
  webview_flutter: ^4.4.1

dev_dependencies:
  alchemist: ^0.7.0
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  chopper_generator: ^7.0.6
  dependency_validator: ^3.2.3
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  mocktail_image_network: ^1.0.0
  very_good_analysis: ^5.1.0


flutter_gen:
  output: lib/app/generated/
  integration:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: assets/l10n/
  output_dir: lib/app/generated/

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/env/
