name: very_good_core
description: A Very Good App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.5"

dependencies:
  animations: ^2.0.11
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  chopper: ^7.4.0
  connectivity_plus: ^6.0.2
  crypto: ^3.0.3
  dartx: ^1.2.0
  device_info_plus: ^10.1.0
  email_validator: ^2.1.17
  faker: ^2.1.0
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.22+1
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.9
  go_router: ^12.1.3
  html_unescape: ^2.0.0
  http: ^1.2.1
  icons_launcher: ^2.1.7
  injectable: ^2.4.1
  intl: ^0.18.1
  intl_utils: ^2.8.7
  json_annotation: ^4.8.1
  logger: ^2.2.0
  package_info_plus: ^7.0.0
  pretty_chopper_logger: ^1.0.11
  responsive_framework: ^1.4.0
  rxdart: ^0.27.7
  safe_device: ^1.1.6
  shared_preferences: ^2.2.3
  skeletonizer: ^1.1.1
  timeago: ^3.6.1
  url_launcher: ^6.2.6
  uuid: ^4.4.0


dev_dependencies:
  alchemist: ^0.7.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  chopper_generator: ^7.4.0
  dependency_validator: ^3.2.3
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  mocktail_image_network: ^1.1.0
  very_good_analysis: ^5.1.0
 

flutter_gen:
  output: lib/app/generated/
  integration:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: assets/l10n/
  output_dir: lib/app/generated/

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/env/
