name: very_good_core
description: A Very Good App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animations: ^2.0.7
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  chopper: ^6.1.1
  connectivity_plus: ^3.0.3
  crypto: ^3.0.2
  dartx: ^1.1.0
  dartz: ^0.10.1
  email_validator: ^2.1.17
  faker: ^2.1.0
  flash: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_secure_storage: ^8.0.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.5.2
  hidable: ^1.0.3
  html_unescape: ^2.0.0
  http: ^0.13.5
  injectable: ^2.1.1
  intl: ^0.17.0
  intl_utils: ^2.8.2
  json_annotation: ^4.8.0
  leak_tracker: ^3.0.2
  logger: ^1.3.0
  path_provider: ^2.0.14
  pretty_chopper_logger: ^1.0.3
  responsive_framework: ^0.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0
  timeago: ^3.3.0
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  webview_flutter: ^4.1.0

dev_dependencies:
  alchemist: ^0.6.0
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  dart_code_metrics: ^5.7.0
  dependency_validator: ^3.2.2
  flutter_gen: ^5.2.0
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^4.0.0+1

flutter_gen:
  output: lib/app/generated/
  integration:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: assets/l10n/
  output_dir: lib/app/generated/

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/env/
