name: generate_domain_driven_bloc

on:
  push:
    paths:
      - tool/generator/**
      - src/**
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "generate-domain-driven-bloc-${{ github.ref_name }}"
  cancel-in-progress: true      

jobs:
  build:
    runs-on: macos-latest
    steps:
      -  uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1.6.0

      - name: Install Dependencies
        working-directory: tool/generator
        run: dart pub get

      - name: Generate Template
        run: dart ./tool/generator/main.dart

      - name: Config Git User
        run: |
          git config user.name VGV Bot
          git config user.email vgvbot@users.noreply.github.com

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: chore/generate-domain_driven_bloc
          commit-message: "chore: generate domain_driven_bloc template"
          title: "chore: generate domain_driven_bloc template"
          body: Please squash and merge me!
          labels: bot
          author: VGV Bot <vgvbot@users.noreply.github.com>
          assignees: vgvbot
          reviewers: Arnooodles
          committer: VGV Bot <vgvbot@users.noreply.github.com>
         
