name: publish_domain_driven_bloc

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/mason_publish.yml@v1
    with:
      working_directory: "brick"
    secrets:
      mason_credentials: ${{ secrets.MASON_CREDENTIALS }}
