name: vulnerability_check

on:
  pull_request:
    branches:
        - main
    paths:
        - "src/my_app/pubspec.yaml"
        - "src/my_app/pubspec.lock"
    
     
    
  
permissions:
    security-events: write
    contents: read
  
jobs:
    scan-pr:
      uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v0.1.0"