name: vulnerability_check

on:
  workflow_dispatch:
  pull_request:
    branches:
        - main
    paths:
        - "src/my_app/pubspec.yaml"
        - "src/my_app/pubspec.lock"
    
concurrency:
  group: "vulnerability-check-${{ github.ref_name }}"
  cancel-in-progress: true         


permissions:
  security-events: write
  contents: read
  actions: read
  
jobs:
    scan-pr:
      uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.0.3"